# Generated by Django 4.1.3 on 2022-12-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service_providerider_registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_name', models.CharField(max_length=50)),
                ('ser_email', models.CharField(max_length=30)),
                ('ser_mobile', models.IntegerField()),
            ],
        ),
    ]
