# Generated by Django 4.1.3 on 2022-12-08 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service_providerider_registrations',
            new_name='service_provider_registrations',
        ),
    ]
