# Generated by Django 4.1.3 on 2022-12-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_service_providerider_registrations_service_provider_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_provider_registrations',
            name='ser_password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_provider_registrations',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
