# Generated by Django 4.1.3 on 2022-12-10 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_provider_registrations_ser_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_descriptions', models.CharField(max_length=1000)),
                ('service_cost', models.FloatField()),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service_provider_registrations')),
            ],
        ),
    ]
