# Generated by Django 4.1.3 on 2022-12-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='provider',
            new_name='username',
        ),
    ]
