# Generated by Django 4.1.3 on 2023-03-18 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_remove_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service_provider_registrations'),
        ),
    ]
