# Generated by Django 4.1.3 on 2022-12-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('provider_name', models.CharField(max_length=100)),
                ('provider_email', models.CharField(max_length=50)),
            ],
        ),
    ]
