# Generated by Django 4.1.3 on 2022-12-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_quries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('provider_name', models.CharField(max_length=100)),
                ('Useremail', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('queries', models.CharField(max_length=700)),
            ],
        ),
        migrations.DeleteModel(
            name='user_services',
        ),
    ]
