# Generated by Django 4.1.3 on 2022-12-16 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_quries_delete_user_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_quries',
            name='username',
        ),
    ]
