# Generated by Django 4.1.3 on 2022-12-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_quries_provider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_quries',
            name='service_name',
            field=models.CharField(max_length=200),
        ),
    ]
