# Generated by Django 4.1.3 on 2022-12-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_quries_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_quries',
            name='user_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_quries',
            name='provider_name',
            field=models.CharField(max_length=100),
        ),
    ]
