# Generated by Django 4.1.3 on 2022-12-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_quries_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_quries',
            name='user_name',
        ),
    ]
