# Generated by Django 4.1.3 on 2022-12-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_quries_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=70)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
