# Generated by Django 4.1.3 on 2023-03-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_register_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_quries',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
