# Generated by Django 4.1.3 on 2023-03-20 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_quries_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_quries',
            name='createdate',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='user_quries',
            name='resloved_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
