# Generated by Django 4.1.3 on 2023-03-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_quries_quer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_quries',
            name='resloved_date',
            field=models.DateTimeField(null=True),
        ),
    ]
