# Generated by Django 4.1.3 on 2023-03-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_alter_food_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
    ]
