# Generated by Django 4.1.3 on 2023-03-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0005_alter_food_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
