# Generated by Django 4.1.3 on 2023-03-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0006_food_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(default='shdfgsjhd', max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_price',
            field=models.FloatField(default=100),
        ),
    ]
